apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: flink
data:
  bootstrap-server: "boot-dbqasg2s.c3.kafka-serverless.us-east-1.amazonaws.com:9098"
  topic-name: "data-ingest"
  aws-region: "us-east-1"
  schema-registry-name: "clickstream-registry"
  schema-name: "clickstream-event-schema"
